Key: 32C7D1D29800014-SM
GameFolder: C:\Games\World of Warcraft
AddonName: HealBotLite
Debug: false
DebugAura: false
DebugSpell: false
DebugPower: false
DebugScan: false
InputDelay: 25
InputDriver: 0
SnapshotHotkey: 0
SnapshotModifier: 0
CastOverlap: 470
ChannelOverlap: 470
AutoAdjustOverlap: true
IconOverlayEnabled: true
IconOverlayX: 1261
IconOverlayY: 919
IconOverlaySize: 40
IconOverlayLocked: false
IconOverlayGameOnly: true
spec_profiles:
  103:
    auto_switch: false
    active_index: 0
    profiles:
      - name: Default
        scenarios: 0
        auto_enabled: true
        values:
          game_mode: 1
          predatory_swiftness_heal_solo_hp_pct: 75
          barkskin_threshold: 59
          use_heart_of_the_wild: true
          stampeding_roar_usage: 1
          survival_instincts_threshold: 55
          innervate_threshold: 50
          skull_bash_delay: 100
          use_potion: true
          use_trinket_2: true
          regrowth_threshold: 35
          stampeding_roar_movement_time: 1
          aoe_threshold: 3
          frenzied_regen_threshold: 30
          shadowmeld_usage: 1
          barkskin_hp_pct: 35
          survival_instincts_hp_pct: 30
          predatory_swiftness_heal_group_hp_pct: 50
          survival_instincts_dmg_pct: 40
          barkskin_dmg_pct: 35
        shared_values:
          healthstone: 50
          interrupt_all: true
          interrupt_pct: 10
          healthpotion: 45
          interrupt_important_pct: 10
          manapotion: 60
          interrupt_mouseover: true
          combat_potion_mplus_min: 18
          combat_potion_enabled: false
          combat_potion_timing: 1
          interrupt_focus: true
  104:
    auto_switch: false
    active_index: 0
    profiles:
      - name: Default
        scenarios: 0
        auto_enabled: true
        values:
          allow_pull_with_mo: false
          auto_purge_enrage: true
          auto_dispel_party: true
          hotw_min_ttd: 10
          hotw_hp_pct: 95
          engine_health_potion: 25
          engine_healthstone: 30
          auto_hotw: true
          ttd_trinkets: 25
        shared_values:
          healthstone: 50
          interrupt_all: true
          interrupt_pct: 25
          healthpotion: 40
          interrupt_important_pct: 20
          manapotion: 60
          combat_potion_mplus_min: 18
          combat_potion_enabled: true
  102:
    auto_switch: false
    active_index: 0
    profiles:
      - name: Default
        scenarios: 0
        auto_enabled: true
        values:
          use_trinket_2: true
          use_trinket_1: true
          inc_min_enemies: 3
          barkskin_hp: 45
          enable_hotw: false
          auto_dispel_party: false
          enable_mouseover_dots: true
          frenzied_regen_hp: 20
          renewal_hp: 30
          hotw_hp: 25
          swap_off_dying: false
          hotw_hp_threshold: 50
          use_potion: true
          ttd_fury_of_elune: 15
          auto_burst: false
          inc_min_combat_time: 6
          inc_min_standing_time: 2
          ttd_incarnation: 25
          ttd_trinkets: 25
          ttd_potion: 25
          auto_purge_enrage: true
          thorn_bloom_threshold: 25
          hotw_bear_hp: 35
          hotw_bear_defensive: false
          engine_auto_combat:
            - 1
            - 2
            - 3
          barkskin_dmg_pct: 45
          engine_health_potion: 30
          burst_once: false
        shared_values:
          healthstone: 50
          interrupt_all: true
          interrupt_pct: 25
          healthpotion: 40
          interrupt_important_pct: 20
          manapotion: 60
          combat_potion_mplus_min: 10
          combat_potion_enabled: true
  105:
    auto_switch: false
    active_index: 0
    profiles:
      - name: Default
        scenarios: 0
        auto_enabled: true
        values:
          innervate_threshold: 75
          manual_tranquility: false
          use_heart_of_the_wild: true
          raid_use_trinket_1: true
          raid_use_potion: true
          use_trinket_2: true
          stampeding_roar_usage: 0
          use_trinket_1: true
          raid_use_trinket_2: true
          swiftmend_threshold: 85
          regrowth_threshold: 90
          emergency_hp: 30
          ironbark_threshold: 75
          frenzied_regen_threshold: 35
          convoke_threshold: 75
          tranquility_threshold: 70
          wild_growth_threshold: 88
          convoke_members: 3
          tranquility_members: 3
          barkskin_threshold: 80
          aoe_threshold: 2
          thorn_bloom_members: 2
        shared_values:
          healthstone: 50
          interrupt_all: true
          interrupt_pct: 25
          healthpotion: 40
          interrupt_important_pct: 20
          manapotion: 60
          combat_potion_mplus_min: 18
          combat_potion_enabled: true
  252:
    auto_switch: false
    active_index: 0
    profiles:
      - name: Default
        scenarios: 0
        auto_enabled: true
        values:
          stampeding_roar_movement_time: 1
          survival_instincts_threshold: 40
          stampeding_roar_usage: 3
          use_trinket_1: false
          frenzied_regen_threshold: 55
          manual_barkskin: false
          use_potion: true
          use_growl: true
          use_trinket_2: false
          auto_incarn_st: false
        shared_values:
          auto_rez: true
          healthpotion: 40
          interrupt_pct: 25
          lootnearby: true
          auto_target_ranged:
            - 0
            - 1
          healthstone: 50
          manapotion: 60
          combat_potion_mplus_min: 18
          interrupt_mouseover: true
          auto_target:
            - 0
            - 1
          auto_combat:
            - 1
            - 2
          interrupt_target: true
          auto_brez: true
          interrupt_all: true
          interrupt_focus: true
          interrupt_important_pct: 20
          los_block_duration: 3
          combat_potion_enabled: true
          combat_potion_difficulty:
            - 15
            - 16
          combat_potion_timing: 0
  250:
    auto_switch: false
    active_index: 0
    profiles:
      - name: Default
        scenarios: 0
        auto_enabled: true
        values:
          darksuccor_solo_hp_pct: 75
          death_pact_hp_pct: 15
          darksuccor_group_hp_pct: 25
          icebound_fortitude_hp_pct: 50
          deathstrike_solo_hp_pct: 50
          icebound_fortitude_dmg_pct: 50
          deathstrike_group_hp_pct: 15
        shared_values:
          auto_rez: true
          healthpotion: 40
          interrupt_pct: 25
          lootnearby: true
          auto_target_ranged:
            - 0
            - 1
          healthstone: 50
          manapotion: 60
          combat_potion_mplus_min: 18
          interrupt_mouseover: true
          auto_target:
            - 0
            - 1
          auto_combat:
            - 1
            - 2
          interrupt_target: true
          auto_brez: true
          interrupt_all: true
          interrupt_focus: true
          interrupt_important_pct: 20
          los_block_duration: 3
          combat_potion_enabled: true
          combat_potion_difficulty:
            - 15
            - 16
          combat_potion_timing: 0
  262:
    auto_switch: false
    active_index: 0
    profiles:
      - name: Default
        scenarios: 0
        auto_enabled: true
        values:
          earth_elemental_hp_pct: 35
          astral_shift_dmg_pct: 50
          aoe_threshold: 3
          engine_loot_nearby: true
          ttd_cooldowns: 20
          astral_shift_hp_pct: 50
          healing_surge_hp_pct: 30
          emergency_stop_casting: true
          healing_surge_ooc_hp_pct: 70
          engine_healthstone: 40
          emergency_hp: 35
          interrupt_min_delay: 150
          auto_burst: true
          use_potion: true
          use_trinket_1: true
          use_trinket_2: true
          engine_affix_devour: true
          mo_cap_totem: true
          ttd_trinkets: 10
          ttd_potion: 15
          auto_cleanse_totem: true
          auto_purge: false
          interrupt_timing: true
          engine_ghost_wolf: true
          interrupt_latency_margin: 250
          cap_totem_aoe: true
          mo_thunderstorm: false
          engine_health_potion: 25
          MO_flame_shock: true
          engine_auto_target:
            - 0
            - 1
        shared_values:
          auto_rez: true
          healthpotion: 25
          interrupt_pct: 25
          lootnearby: true
          auto_target_ranged:
            - 0
            - 1
          healthstone: 40
          manapotion: 40
          combat_potion_mplus_min: 0
          interrupt_mouseover: true
          auto_target:
            - 0
            - 1
          auto_combat:
            - 1
            - 2
          interrupt_target: true
          auto_brez: true
          interrupt_all: false
          interrupt_focus: true
          interrupt_important_pct: 50
          los_block_duration: 3
          combat_potion_enabled: true
          combat_potion_difficulty:
            - 15
            - 16
          combat_potion_timing: 0
shared_config:
  interrupt_all: true
  healthstone: 50
  healthpotion: 40
  interrupt_pct: 25
  manapotion: 60
  interrupt_important_pct: 20
  combat_potion_mplus_min: 18
  combat_potion_enabled: true
toggle_hotkeys:
  105:
    force_convoke:
      scancode: 44
      modifier: 0
    spread_rejuvs:
      scancode: 45
      modifier: 0
    force_dps:
      scancode: 44
      modifier: 0
    manual_tranquility:
      scancode: 44
      modifier: 0
    force_spread:
      scancode: 45
      modifier: 0
    manual_convoke:
      scancode: 44
      modifier: 0
    rejuvenation_spread:
      scancode: 45
      modifier: 0
    raid_force_spread:
      scancode: 45
      modifier: 0
    ooc_abundance:
      scancode: 45
      modifier: 0
  104:
    use_incarnation:
      scancode: 45
      modifier: 0
    starfall_combo:
      scancode: 45
      modifier: 0
    pool_rage:
      scancode: 44
      modifier: 0
    use_hotw:
      scancode: 45
      modifier: 0
    use_feral_frenzy:
      scancode: 45
      modifier: 0
  102:
    burst_toggle:
      scancode: 59
      modifier: 0
  103:
    burst_toggle:
      scancode: 45
      modifier: 0
  268:
    dps_mode:
      scancode: 45
      modifier: 0
    spam_purifying_brew:
      scancode: 44
      modifier: 0
selected_rotation:
  103: C:\Games\Python\Rotations\FerrazFeral.yaml
  102: C:\Games\Python\Rotations\FerrazBalanceRaid.yaml
  262: C:\Games\Python\Rotations\FerrazShamanEle.yaml
  104: C:\Games\Python\Rotations\FerrazGuardianElune.yaml
  105: C:\Games\Python\Rotations\FerrazRestoDruid.yaml
selected_community_rotation_name:
  104: "[Community] Khan No Apex Guardian Druid (1.0.7) - Khan"
  102: "[Community] Balance Druid Ferraz Raid (1.0) - Ferraz"
  103: "[Community] Feral Druid Ferraz M+ (5.0) - Ferraz"
queue_sounds_enabled: true
queue_volume_on: 0.600000024
queue_volume_off: 0.600000024
queue_volume_deny: 0.600000024
queue_clear_hotkey: 59
queue_clear_modifier: 0
queue_icons_mode: 2
queue_icons_size: 35
queue_icons_grow: 0
queue_icons_max: 3
queue_icons_x: 1221
queue_icons_y: 976
queue_icons_locked: true
queue_bindings:
  104:
    - name: Frenzie
      scancode: 4
      modifier: 0
      admit: cooldown.frenzied_regeneration.up
      expire: ""
      unqueue_on_cast: true
      ttl: 0
      priority_list: false
      enabled: true
      steps:
        - spell: 22842
          target: 0
          if: ""
    - name: Thorn
      scancode: 5
      modifier: 0
      admit: cooldown.thorn_bloom.up
      expire: ""
      unqueue_on_cast: true
      ttl: 0
      priority_list: false
      enabled: true
      steps:
        - spell: 1237885
          target: 0
          if: ""
    - name: Lunar
      scancode: 41
      modifier: 0
      admit: cooldown.lunar_beam.up
      expire: ""
      unqueue_on_cast: true
      ttl: 0
      priority_list: false
      enabled: true
      steps:
        - spell: 204066
          target: 0
          if: ""
    - name: Vortex
      scancode: 24
      modifier: 0
      admit: cooldown.ursols_vortex.up
      expire: ""
      unqueue_on_cast: true
      ttl: 0
      priority_list: false
      enabled: true
      steps:
        - spell: 102793
          target: 0
          if: ""
    - name: Typhoon
      scancode: 33
      modifier: 0
      admit: cooldown.typhoon.up
      expire: ""
      unqueue_on_cast: true
      ttl: 0
      priority_list: false
      enabled: true
      steps:
        - spell: 132469
          target: 0
          if: ""
    - name: Roar
      scancode: 35
      modifier: 0
      admit: cooldown.stampeding_roar.up
      expire: ""
      unqueue_on_cast: true
      ttl: 0
      priority_list: false
      enabled: true
      steps:
        - spell: 77761
          target: 0
          if: ""
  102:
    - name: Thorn
      scancode: 5
      modifier: 0
      admit: cooldown.thorn_bloom.up
      expire: ""
      unqueue_on_cast: true
      ttl: 0
      priority_list: false
      enabled: true
      steps:
        - spell: 1237885
          target: 0
          if: ""
    - name: Vortex
      scancode: 24
      modifier: 0
      admit: cooldown.ursols_vortex.up
      expire: ""
      unqueue_on_cast: true
      ttl: 0
      priority_list: false
      enabled: true
      steps:
        - spell: 102793
          target: 0
          if: ""
    - name: Typhoon
      scancode: 33
      modifier: 0
      admit: cooldown.typhoon.up
      expire: ""
      unqueue_on_cast: true
      ttl: 0
      priority_list: false
      enabled: true
      steps:
        - spell: 132469
          target: 0
          if: ""
    - name: Roar
      scancode: 35
      modifier: 0
      admit: cooldown.stampeding_roar.up
      expire: ""
      unqueue_on_cast: true
      ttl: 0
      priority_list: false
      enabled: true
      steps:
        - spell: 106898
          target: 0
          if: ""
    - name: Incarnation
      scancode: 45
      modifier: 0
      admit: cooldown.incarnation_chosen_of_elune.up
      expire: ""
      unqueue_on_cast: true
      ttl: 0
      priority_list: false
      enabled: true
      steps:
        - spell: 102560
          target: 0
          if: "cooldown.fury_of_elune.ready&(trinket_1.ready|trinket_2.ready)&!buff.incarnation_chosen_of_elune.up"
  105:
    - name: Thorn
      scancode: 5
      modifier: 0
      admit: cooldown.thorn_bloom.up
      expire: ""
      unqueue_on_cast: true
      ttl: 0
      priority_list: false
      enabled: true
      steps:
        - spell: 1237885
          target: 0
          if: ""
    - name: Vortex
      scancode: 24
      modifier: 0
      admit: cooldown.ursols_vortex.up
      expire: ""
      unqueue_on_cast: true
      ttl: 0
      priority_list: false
      enabled: true
      steps:
        - spell: 102793
          target: 0
          if: ""
    - name: Typhoon
      scancode: 33
      modifier: 0
      admit: cooldown.typhoon.up
      expire: ""
      unqueue_on_cast: true
      ttl: 0
      priority_list: false
      enabled: true
      steps:
        - spell: 132469
          target: 0
          if: ""
    - name: Roar
      scancode: 35
      modifier: 0
      admit: cooldown.stampeding_roar.up
      expire: ""
      unqueue_on_cast: true
      ttl: 0
      priority_list: false
      enabled: true
      steps:
        - spell: 106898
          target: 0
          if: ""
    - name: Tranquility
      scancode: 41
      modifier: 0
      admit: cooldown.tranquility.up
      expire: ""
      unqueue_on_cast: true
      ttl: 0
      priority_list: false
      enabled: true
      steps:
        - spell: 740
          target: 0
          if: ""
    - name: Convoke
      scancode: 2
      modifier: 0
      admit: cooldown.convoke_the_spirits.up
      expire: ""
      unqueue_on_cast: true
      ttl: 0
      priority_list: false
      enabled: true
      steps:
        - spell: 391528
          target: 0
          if: "!buff.cat_form.up"
    - name: Wild
      scancode: 3
      modifier: 0
      admit: cooldown.wild_growth.up
      expire: ""
      unqueue_on_cast: true
      ttl: 0
      priority_list: false
      enabled: true
      steps:
        - spell: 48438
          target: 0
          if: ""
  103:
    - name: Thorn
      scancode: 5
      modifier: 0
      admit: cooldown.thorn_bloom.up
      expire: ""
      unqueue_on_cast: true
      ttl: 0
      priority_list: false
      enabled: true
      steps:
        - spell: 1237885
          target: 0
          if: ""
    - name: Vortex
      scancode: 24
      modifier: 0
      admit: cooldown.ursols_vortex.up
      expire: ""
      unqueue_on_cast: true
      ttl: 0
      priority_list: false
      enabled: true
      steps:
        - spell: 102793
          target: 0
          if: ""
    - name: Typhoon
      scancode: 33
      modifier: 0
      admit: cooldown.typhoon.up
      expire: ""
      unqueue_on_cast: true
      ttl: 0
      priority_list: false
      enabled: true
      steps:
        - spell: 132469
          target: 0
          if: ""
    - name: Roar
      scancode: 35
      modifier: 0
      admit: cooldown.stampeding_roar.up
      expire: ""
      unqueue_on_cast: true
      ttl: 0
      priority_list: false
      enabled: true
      steps:
        - spell: 106898
          target: 0
          if: ""