Key: 32C7D1D29800014-SM
GameFolder: C:\Games\World of Warcraft
AddonName: WeakAurasModule
Debug: false
DebugAura: false
DebugSpell: false
DebugPower: false
InputDelay: 25
CastOverlap: 400
ChannelOverlap: 400
AutoAdjustOverlap: true
IconOverlayEnabled: true
IconOverlayX: 100
IconOverlayY: 100
IconOverlaySize: 40
IconOverlayLocked: false
IconOverlayGameOnly: true
rotation_config:
  103:
    game_mode: 1
selected_rotation:
  105: C:\Games\Python\Rotations\FerrazRestoDruid.yaml
  103: C:\Games\Python\Rotations\FerrazFeral.yaml