Key: 32C7D1D29800014-SM
GameFolder: C:\Games\World of Warcraft
AddonName: WeakAurasModule
Debug: false
DebugAura: false
DebugSpell: false
DebugPower: false
InputDelay: 25
CastOverlap: 400
ChannelOverlap: 400
AutoAdjustOverlap: true
IconOverlayEnabled: true
IconOverlayX: 1257
IconOverlayY: 844
IconOverlaySize: 40
IconOverlayLocked: true
IconOverlayGameOnly: true
rotation_config:
  103:
    game_mode: 1
    use_heart_of_the_wild: true
  104:
    hero_tree: 1
  105:
    symbiotic_unit_select:
      []
shared_config:
  interrupt_all: true
  interrupt_pct: 35
selected_rotation:
  103: C:\Games\Python\Rotations\FerrazFeral.yaml
  104: C:\Games\Python\Rotations\FerrazGuardian.yaml
  105: C:\Games\Python\Rotations\FerrazRestoDruid.yaml